import Nav from './Nav';
import Head from 'next/head';
import 'bulma/css/bulma.min.css';

const Layout = ({children}) => {
    return (
      <>
        <Head>
          <title>BookTok Project 2</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>

        <div className="columns">
            <div className="column has-background-danger-light is-one-quarter">
                <section className='section'>
                    <Nav />
                </section>
            </div>
            <div className="column">            
                <section className="section">
                    {children}
                </section>
            </div>
        </div>

        {/* <h1>"splash page"</h1> */}

        {/* <SignIn path="/" routing="path" signUpUrl="/sign-up" redirectUrl='home'/> */}

      </>
    )
}

export default Layout